# Generated by Django 5.2.1 on 2025-09-14 17:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email_corporativo', models.EmailField(max_length=254, unique=True, verbose_name='Email Corporativo')),
                ('agencia', models.CharField(choices=[('001', '001 - Matriz Patrocinio'), ('002', '002 - Agência Uberlândia'), ('003', '003 - Agência Guimarânia'), ('004', '004 - Agência Coromandael')], max_length=3, verbose_name='Agência')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('tamanho_camiseta', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('BL_P', 'Baby Look P'), ('BL_M', 'Baby Look M'), ('BL_G', 'Baby Look G'), ('BL_GG', 'Baby Look GG')], max_length=5, verbose_name='Tamanho da Camiseta')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo a desempenhar no evento')),
                ('experiencia_anterior', models.TextField(blank=True, help_text='Experiências anteriores em voluntariado', null=True, verbose_name='Experiência Anterior')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['email_corporativo'], name='vmm_volunta_email_c_d63905_idx'), models.Index(fields=['cpf'], name='vmm_volunta_cpf_5d681d_idx'), models.Index(fields=['status'], name='vmm_volunta_status_f06f05_idx')],
            },
        ),
    ]
