# Generated by Django 5.2.6 on 2025-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='experiencia_anterior',
            field=models.TextField(blank=True, help_text='Experiências anteriores em voluntariado', verbose_name='Experiência Anterior'),
        ),
    ]
