# Generated by Django 5.2.6 on 2025-10-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0002_alter_voluntario_experiencia_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Identificação do Veículo')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('pickup', 'Pickup')], max_length=20, verbose_name='Tipo')),
                ('capacidade', models.IntegerField(default=5, verbose_name='Capacidade de Passageiros')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em Manutenção'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo no Sistema'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo Principal'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='experiencia_anterior',
            field=models.TextField(blank=True, null=True, verbose_name='Experiência Anterior'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('responsavel_escola', models.CharField(max_length=255, verbose_name='Responsável da Escola')),
                ('telefone_responsavel', models.CharField(max_length=15, verbose_name='Telefone do Responsável')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('qtd_tv', models.IntegerField(default=0, verbose_name='Quantidade de TVs')),
                ('qtd_computador', models.IntegerField(default=0, verbose_name='Quantidade de Computadores')),
                ('status', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20, verbose_name='Status do Evento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_por', models.CharField(blank=True, max_length=255, verbose_name='Criado Por')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmm.veiculo', verbose_name='Veículo Designado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_evento', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VoluntarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('coordenador', 'Coordenador do Evento'), ('motorista', 'Motorista'), ('apoio_logistico', 'Apoio Logístico'), ('palestrante', 'Palestrante'), ('monitor', 'Monitor de Atividades'), ('fotografo', 'Fotógrafo/Registro'), ('atendimento', 'Atendimento ao Público'), ('outro', 'Outro')], max_length=30, verbose_name='Função no Evento')),
                ('funcao_customizada', models.CharField(blank=True, help_text="Use quando a função for 'Outro'", max_length=100, verbose_name='Descrição Customizada da Função')),
                ('presenca', models.CharField(choices=[('confirmado', 'Confirmado'), ('presente', 'Presente'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20, verbose_name='Status de Presença')),
                ('vai_no_veiculo', models.BooleanField(default=False, verbose_name='Irá no Veículo Designado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmm.evento')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmm.voluntario')),
            ],
            options={
                'verbose_name': 'Voluntário no Evento',
                'verbose_name_plural': 'Voluntários nos Eventos',
                'ordering': ['evento__data_evento', 'funcao'],
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_evento', 'hora_inicio'], name='vmm_evento_data_ev_8fc89c_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status'], name='vmm_evento_status_db6a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='voluntarioevento',
            index=models.Index(fields=['evento', 'voluntario'], name='vmm_volunta_evento__837107_idx'),
        ),
        migrations.AddIndex(
            model_name='voluntarioevento',
            index=models.Index(fields=['presenca'], name='vmm_volunta_presenc_95c952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voluntarioevento',
            unique_together={('evento', 'voluntario')},
        ),
    ]
