# Generated by Django 5.2.6 on 2025-10-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0003_veiculo_alter_voluntario_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarioevento',
            name='funcao',
            field=models.CharField(choices=[('coordenador', 'Coordenador do Evento'), ('motorista', 'Motorista'), ('apoio_logistico', 'Apoio Logístico'), ('triagem', 'Triagem'), ('monitor', 'Monitor de Atividades'), ('fotografo', 'Fotógrafo/Registro'), ('outro', 'Outro')], max_length=30, verbose_name='Função no Evento'),
        ),
        migrations.AlterField(
            model_name='voluntarioevento',
            name='vai_no_veiculo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmm.evento')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_dirigidos', to='vmm.voluntario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmm.veiculo')),
            ],
            options={
                'unique_together': {('evento', 'veiculo')},
            },
        ),
        migrations.AddField(
            model_name='voluntarioevento',
            name='evento_veiculo',
            field=models.ForeignKey(blank=True, help_text='Qual veículo o voluntário vai utilizar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmm.eventoveiculo'),
        ),
    ]
