# Generated by Django 5.2.6 on 2025-10-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0004_alter_voluntarioevento_funcao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoveiculo',
            options={'verbose_name': 'Veículo no Evento', 'verbose_name_plural': 'Veículos nos Eventos'},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_cadastro',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='veiculo',
        ),
        migrations.AlterField(
            model_name='voluntarioevento',
            name='evento_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vmm.eventoveiculo'),
        ),
        migrations.AlterField(
            model_name='voluntarioevento',
            name='funcao_customizada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição Customizada da Função'),
        ),
        migrations.AlterField(
            model_name='voluntarioevento',
            name='presenca',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('presente', 'Presente'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status de Presença'),
        ),
    ]
