# Generated by Django 5.2.6 on 2025-10-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0005_alter_eventoveiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo no Sistema'),
        ),
    ]
