# Generated by Django 5.2.6 on 2025-10-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmm', '0006_evento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='eventoveiculo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='eventoveiculo',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='voluntarioevento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='voluntarioevento',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['ativo'], name='vmm_evento_ativo_ce5bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoveiculo',
            index=models.Index(fields=['ativo'], name='vmm_eventov_ativo_22db0d_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['ativo'], name='vmm_veiculo_ativo_db870b_idx'),
        ),
        migrations.AddIndex(
            model_name='voluntario',
            index=models.Index(fields=['ativo'], name='vmm_volunta_ativo_4bf07f_idx'),
        ),
        migrations.AddIndex(
            model_name='voluntarioevento',
            index=models.Index(fields=['ativo'], name='vmm_volunta_ativo_0459f9_idx'),
        ),
    ]
